services:
  postgres:
    image: postgres:alpine
    container_name: pg_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - music_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --requirepass "${REDIS_PASSWORD}"
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: minio_music
    restart: unless-stopped
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_UI_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ADMIN}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_SCHEME=https
      - SSL_CERT_FILE=/root/.minio/certs/public.crt
    volumes:
      - minio_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .minio/certs:/root/.minio/certs
      - .mc/certs:/root/.mc/certs
    entrypoint:
      - "sh"
      - "-c"
      - |
        minio server /data --console-address ":9001" --compat &
        MINIO_PID=$!
        chown root:root /root/.minio/certs/public.crt
        chown root:root /root/.minio/certs/private.key
        until curl -s https://localhost:9000/minio/health/live; do
          echo -ne "Waiting for Minio to start...\r"
          sleep 1
        done
        mc alias set local https://localhost:9000 ${MINIO_ADMIN} ${MINIO_PASSWORD}
        mc mb local/music;
        wait ${MINIO_PID}


volumes:
  music_data:
    name: music_data
  redis_data:
    name: redis_data
  minio_data:
    name: minio_data
