version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: pg_db
    restart: unless-stopped
    env_file:
    - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - music_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6363:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app_network

volumes:
  music_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge